### ISSUE TITLE
API Error parsing is broken (as is specifying translatedLanguage)

### ISSUE THREAD

**Issue by fake-name** [EMACC99/mangadex#30]
**Describe the bug**

The error handling is broken, and throws an exception. Additionally, I cannot see how it could have ever worked.

**To Reproduce**

```
import mangadex

def test():

	api = mangadex.Api()
	items = api.get_manga_list(translatedLanguage=['en'])

if __name__ == "__main__":

	test()

```

Results:

```
durr@nmscrape /m/S/MangaCMS> python3 wat.py
Error message: The api responded with the error
<Response [400]>
{"result":"error","errors":[{"id":"9c346772-7b14-5982-b4b6-7b5888522762","status":400,"title":"validation_exception","detail":"Error validating : The property translatedLanguage is not defined and the definition does not allow additional properties","context":null}]}

Traceback (most recent call last):
  File "wat.py", line 67, in <module>
    test()
  File "wat.py", line 63, in test
    items = api.get_manga_list(translatedLanguage=['en'])
  File "/usr/local/lib/python3.6/dist-packages/mangadex/api.py", line 101, in get_manga_list
    resp = URLRequest.request_url(url, 'GET', params=params, timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/mangadex/url_models.py", line 59, in request_url
    raise ApiError(resp)
  File "/usr/local/lib/python3.6/dist-packages/mangadex/errors.py", line 21, in __init__
    self.details = self.resp.text["detail"]
TypeError: string indices must be integers

````

Note that I have inserted additional print statements into `errors.py`. They are the source of all the stdout before the traceback.

So several things are going on:

 - Handling of `translatedLanguage` in the API call is failing (something weird is going on with `__parse_manga_params`)
 - I cannot see how `ApiError` could ever have worked. `response.text` is (and as far as I know has *always* been) just a string. You cannot slice that with another string
 - Even if it were replaced with `response.json()`, the structure of the error doesn't match the structure that the `ApiError()` class expects. This may just be due to upstream changes in mangadex.

**Desktop (please complete the following information):**

- OS: Linux
- Python version: 3.6.9
- Installed from: pypi, latest version

**Comment by fake-name** [comment]
Shoving debugging into requests, the insertion of brackets into the request *is* working:

```
durr@nmscrape /m/S/MangaCMS> python3 wat.py
Starting new HTTPS connection (1): api.mangadex.org:443
send: b'GET /manga?translatedLanguage%5B%5D=en HTTP/1.1\r\nHost: api.mangadex.org\r\nUser-Agent: python-requests/2.21.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: content-type: application/json
header: cache-control: no-cache, private
header: date: Mon, 08 May 2023 08:28:02 GMT
header: x-cache: MISS
header: content-length: 267
header: access-control-allow-credentials: true
header: access-control-expose-headers: *
header: vary: Origin
header: server: MangaDex
header: via: HTTP/1.1 NA-WEST-L1x1
header: x-request-id: 70bf52cf-68a7-4347-aeb3-11c9f4564cca
header: permissions-policy: fullscreen=(self)
header: referrer-policy: strict-origin
header: x-content-type-options: nosniff
header: x-xss-protection: 1; mode=block
header: x-frame-options: DENY
header: cross-origin-embedder-policy: unsafe-none
header: cross-origin-opener-policy: same-origin-allow-popups
header: cross-origin-resource-policy: cross-origin
header: strict-transport-security: max-age=63072000; includeSubDomains; preload
header: alt-svc: h3=":443"; ma=86400
https://api.mangadex.org:443 "GET /manga?translatedLanguage%5B%5D=en HTTP/1.1" 400 267
Error message: The api responded with the error
<Response [400]>
{"result":"error","errors":[{"id":"9c346772-7b14-5982-b4b6-7b5888522762","status":400,"title":"validation_exception","detail":"Error validating : The property translatedLanguage is not defined and the definition does not allow additional properties","context":null}]}

Traceback (most recent call last):
  File "wat.py", line 30, in <module>
    test()
  File "wat.py", line 26, in test
    items = api.get_manga_list(translatedLanguage=['en'])
  File "/usr/local/lib/python3.6/dist-packages/mangadex/api.py", line 101, in get_manga_list
    resp = URLRequest.request_url(url, 'GET', params=params, timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/mangadex/url_models.py", line 59, in request_url
    raise ApiError(resp)
  File "/usr/local/lib/python3.6/dist-packages/mangadex/errors.py", line 21, in __init__
    self.details = self.resp.text["detail"]
TypeError: string indices must be integers

```

**Comment by fake-name** [comment]
Ok, digging further, the `/manga` endpoint has renamed the `translatedLanguage` parameter to `availableTranslatedLanguage`, which is the cause of that issue.

**Comment by EMACC99** [comment]
Hello, thanks for bringing this up. I will push a fix for this, however, the API error handling might take some more time. I admit that some parts need a rewrite to function better.

**Comment by DavisGoglin** [comment]
This change has unfortunately broken the `manga_feed` api, since that parameter is still named `translatedLanguage`. It looks like the `/manga` endpoint is the only one that had this change. 

Here is a test:

```python
    def test_GetMangaFeedTranslated(self):
        self.api.manga_feed(manga_id="0e017a08-835a-4cbe-ba63-576d5010a5a0", translatedLanguage=["en"])
```

**Comment by lasersPew** [comment]
According to https://api.mangadex.org/docs/swagger.html#/Manga/get-search-manga, translatedLanguages has moved onto availableTranslatedLanguages
